// Header file for the ColorMatch application
// This file is generated by the ColorMatch Application in Learn Mode

// calibration data
sensorData sdBlack = {2940, 2570, 2780};
sensorData sdWhite = {6100, 5610, 6110};

// Color Table for matching
typedef struct
{
  char    name[9];  // color name 8+nul
  colorData rgb;    // RGB value
} colorTable;

colorTable ct[] =
{
  {"WHITE", {255, 255, 251} },
  {"BLACK", {0, 0, 0} },
  {"YELLOW", {220, 154, 68} },
  {"GREEN", {101, 99, 49} },
};
	